"""AntiAIFilter — heuristická obrana doporučení/trendů proti AI-generovanému
hudebnímu spamu (Suno, Udio a podobné hromadné generátory), který zaplavuje
ListenBrainz sitewide/uživatelské statistiky i JSPF doporučení.

Backend nemá žádný oficiální "je tohle AI" signál (ListenBrainz/MusicBrainz
ho nevystavují) -- jde o best-effort heuristiky nad tím, co `/1/stats/*` a
JSPF doporučení reálně vrací (jméno interpreta/alba/skladby, MBID), ne o
spolehlivou detekci. Cíl je odfiltrovat zjevný spam, ne dokázat "je/není AI"
u hraničních případů -- radši nechat proklouznout nejednoznačnou položku, než
schovat legitimní hudbu neznámého interpreta.
"""

from __future__ import annotations

import re
from collections import Counter
from dataclasses import dataclass, field
from typing import Any

# Platformy/vydavatelé notoricky spojení s hromadně generovaným AI spamem na
# streamovacích službách -- shoda kdekoliv ve jméně interpreta/alba/skladby.
KNOWN_AI_PLATFORM_KEYWORDS: frozenset[str] = frozenset(
    {
        "suno",
        "udio",
        "aiva",
        "boomy",
        "soundraw",
        "amper music",
        "aimi",
        "mubert",
        "loudly ai",
        "beatoven",
        "riffusion",
    }
)

# Fráze, které samy o sobě prozrazují AI-generovaný obsah, i bez konkrétní
# značky platformy.
SUSPICIOUS_PHRASES: frozenset[str] = frozenset(
    {
        "ai generated",
        "ai-generated",
        "generated by ai",
        "artificial intelligence music",
        "no copyright ai",
        "ai music channel",
        "ai cover",
        "ai remix",
        "created by artificial intelligence",
    }
)

_WHITESPACE_RE = re.compile(r"\s+")


def _normalize(text: str) -> str:
    return _WHITESPACE_RE.sub(" ", text).strip().lower()


@dataclass
class AntiAIFilter:
    """`max_tracks_per_unknown_artist` řeší druhou heuristiku ze zadání --
    "masová alba o desítkách skladeb od neznámého interpreta" se v jednom
    stažení žebříčku/doporučení projeví jako jeden `artist_name` bez MBID
    opakovaně se vyskytující přes mnoho položek. Jednotlivé volání
    `/recommendations/*` nemá historii napříč časem (to by vyžadovalo
    ukládat stav), takže "rychlý sled vydání" aproximujeme počtem výskytů
    v rámci jednoho batche -- slabší signál, ale bez další MusicBrainz
    závislosti navíc k tomu, co už batch nese.
    """

    max_tracks_per_unknown_artist: int = 4
    blocked_keywords: frozenset[str] = field(default_factory=lambda: KNOWN_AI_PLATFORM_KEYWORDS)
    blocked_phrases: frozenset[str] = field(default_factory=lambda: SUSPICIOUS_PHRASES)

    def is_blocked_text(self, *texts: str | None) -> bool:
        for text in texts:
            if not text:
                continue
            normalized = _normalize(text)
            if any(keyword in normalized for keyword in self.blocked_keywords):
                return True
            if any(phrase in normalized for phrase in self.blocked_phrases):
                return True
        return False

    def filter_stats_entries(self, entries: list[dict[str, Any]]) -> list[dict[str, Any]]:
        """Vstup: syrové položky z `/1/stats/sitewide|user/*/recordings`
        (klíče `artist_name`, `track_name`, `release_name`, `artist_mbids`).
        Volá se PŘED upsertem do katalogu, aby se spam vůbec nedostal do DB.
        """
        artist_counts: Counter[str] = Counter()
        cleaned: list[dict[str, Any]] = []

        for entry in entries:
            artist_name = entry.get("artist_name") or ""
            track_name = entry.get("track_name") or ""
            release_name = entry.get("release_name") or ""

            if self.is_blocked_text(artist_name, track_name, release_name):
                continue

            key = _normalize(artist_name)
            has_mbid = bool(entry.get("artist_mbids"))
            if key:
                artist_counts[key] += 1
                if not has_mbid and artist_counts[key] > self.max_tracks_per_unknown_artist:
                    continue  # "masové album" vzorec -- stejný neznámý interpret zaplavuje batch

            cleaned.append(entry)

        return cleaned

    def is_blocked_jspf_track(self, track: dict[str, Any]) -> bool:
        """JSPF (`daily-jams`/`weekly-exploration`) má jiný tvar (`title`,
        `creator`) než stats entries -- samostatná metoda místo přetěžování
        `filter_stats_entries`, ať volající kód (`_resolve_jspf_track`)
        zůstane čitelný."""
        return self.is_blocked_text(track.get("title"), track.get("creator"))
